version: "3.9"

services:
  api:
    build: .
    container_name: inventory-api
    ports:
      - "3000:3000"       # Host Port : Container Port
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
